# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-07-02 01:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Deuda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acreedor', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('monto', models.IntegerField()),
                ('status', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=200)),
                ('apellido1', models.CharField(max_length=100)),
                ('apellido2', models.CharField(max_length=100)),
                ('estadocivil', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('fecha_nac', models.DateTimeField(auto_now=True)),
                ('deuda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='deudas.Deuda')),
            ],
        ),
    ]
